name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Add checkout
        uses: actions/checkout@master
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0
      - name: MSBuild
        working-directory: ScopeOnMicrocontroller
        run: msbuild ScopeOnMicrocontroller.csproj
